[project]
name = "shepherd"
version = "1.0.0"
description = "A shared platform for Translator ARAs"
authors = [{ name = "Max Wang", email = "max@covar.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "fastapi",
  "httpx==0.28.1",
  "uvicorn[standard]",
  "redis~=5.2",
  "orjson~=3.10",
  "psycopg[binary]~=3.1",
  "psycopg_pool~=3.2",
  "pydantic~=2.11",
  "pydantic-settings~=2.9",
  "python-dotenv~=1.0",
  "pyyaml~=6.0",
  "zstandard~=0.23"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["shepherd_utils", "workers", "shepherd_server"]
include = ["shepherd_utils.*", "workers.*", "shepherd_server.*"]

[tool.setuptools.package-data]
shepherd_utils = ["*.yml"]
