# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server import util


class AllowDenyConstraint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: a list of values which are to either be allowed (ANY) or denied (ALL).
    """

    def __init__(self, behavior=None, values=None):  # noqa: E501
        """AllowDenyConstraint - a model defined in OpenAPI

        :param behavior: The behavior of this AllowDenyConstraint.  # noqa: E501
        :type behavior: str
        :param values: The values of this AllowDenyConstraint.  # noqa: E501
        :type values: List[str]
        """
        self.openapi_types = {
            'behavior': str,
            'values': List[str]
        }

        self.attribute_map = {
            'behavior': 'behavior',
            'values': 'values'
        }

        self._behavior = behavior
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'AllowDenyConstraint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllowDenyConstraint of this AllowDenyConstraint.  # noqa: E501
        :rtype: AllowDenyConstraint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def behavior(self):
        """Gets the behavior of this AllowDenyConstraint.

        ALLOW or DENY.  # noqa: E501

        :return: The behavior of this AllowDenyConstraint.
        :rtype: str
        """
        return self._behavior

    @behavior.setter
    def behavior(self, behavior):
        """Sets the behavior of this AllowDenyConstraint.

        ALLOW or DENY.  # noqa: E501

        :param behavior: The behavior of this AllowDenyConstraint.
        :type behavior: str
        """
        if behavior is None:
            raise ValueError("Invalid value for `behavior`, must not be `None`")  # noqa: E501

        self._behavior = behavior

    @property
    def values(self):
        """Gets the values of this AllowDenyConstraint.

        The values to allow or deny.  # noqa: E501

        :return: The values of this AllowDenyConstraint.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this AllowDenyConstraint.

        The values to allow or deny.  # noqa: E501

        :param values: The values of this AllowDenyConstraint.
        :type values: List[str]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values
