# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server.models.any_type import AnyType
from shepherd_utils.arax.openapi_server.models.message import Message
from shepherd_utils.arax.openapi_server import util

from shepherd_utils.arax.openapi_server.models.any_type import AnyType  # noqa: E501
from shepherd_utils.arax.openapi_server.models.message import Message  # noqa: E501

class AsyncQuery(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: log_level / bypass_cache moved into `parameters`.
    """

    def __init__(self, callback=None, message=None, parameters=None, workflow=None, submitter=None):  # noqa: E501
        """AsyncQuery - a model defined in OpenAPI

        :param callback: The callback of this AsyncQuery.  # noqa: E501
        :type callback: str
        :param message: The message of this AsyncQuery.  # noqa: E501
        :type message: Message
        :param parameters: The parameters of this AsyncQuery.  # noqa: E501
        :type parameters: object
        :param workflow: The workflow of this AsyncQuery.  # noqa: E501
        :type workflow: List[AnyType]
        :param submitter: The submitter of this AsyncQuery.  # noqa: E501
        :type submitter: str
        """
        self.openapi_types = {
            'callback': str,
            'message': Message,
            'parameters': object,
            'workflow': List[AnyType],
            'submitter': str
        }

        self.attribute_map = {
            'callback': 'callback',
            'message': 'message',
            'parameters': 'parameters',
            'workflow': 'workflow',
            'submitter': 'submitter'
        }

        self._callback = callback
        self._message = message
        self._parameters = parameters
        self._workflow = workflow
        self._submitter = submitter

    @classmethod
    def from_dict(cls, dikt) -> 'AsyncQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AsyncQuery of this AsyncQuery.  # noqa: E501
        :rtype: AsyncQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def callback(self):
        """Gets the callback of this AsyncQuery.

        Upon completion, this server will send a POST request to the callback URL.  # noqa: E501

        :return: The callback of this AsyncQuery.
        :rtype: str
        """
        return self._callback

    @callback.setter
    def callback(self, callback):
        """Sets the callback of this AsyncQuery.

        Upon completion, this server will send a POST request to the callback URL.  # noqa: E501

        :param callback: The callback of this AsyncQuery.
        :type callback: str
        """
        if callback is None:
            raise ValueError("Invalid value for `callback`, must not be `None`")  # noqa: E501

        self._callback = callback

    @property
    def message(self):
        """Gets the message of this AsyncQuery.

        The query Message is a serialization of the user request.  # noqa: E501

        :return: The message of this AsyncQuery.
        :rtype: Message
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this AsyncQuery.

        The query Message is a serialization of the user request.  # noqa: E501

        :param message: The message of this AsyncQuery.
        :type message: Message
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def parameters(self):
        """Gets the parameters of this AsyncQuery.

        Query-time parameters (timeout, log_level, bypass_cache, ...).  # noqa: E501

        :return: The parameters of this AsyncQuery.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this AsyncQuery.

        Query-time parameters (timeout, log_level, bypass_cache, ...).  # noqa: E501

        :param parameters: The parameters of this AsyncQuery.
        :type parameters: object
        """

        self._parameters = parameters

    @property
    def workflow(self):
        """Gets the workflow of this AsyncQuery.

        List of workflow steps to be executed.  # noqa: E501

        :return: The workflow of this AsyncQuery.
        :rtype: List[AnyType]
        """
        return self._workflow

    @workflow.setter
    def workflow(self, workflow):
        """Sets the workflow of this AsyncQuery.

        List of workflow steps to be executed.  # noqa: E501

        :param workflow: The workflow of this AsyncQuery.
        :type workflow: List[AnyType]
        """

        self._workflow = workflow

    @property
    def submitter(self):
        """Gets the submitter of this AsyncQuery.

        Any string for self-identifying the submitter of a query.  # noqa: E501

        :return: The submitter of this AsyncQuery.
        :rtype: str
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this AsyncQuery.

        Any string for self-identifying the submitter of a query.  # noqa: E501

        :param submitter: The submitter of this AsyncQuery.
        :type submitter: str
        """

        self._submitter = submitter
