# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server import util


class AuxiliaryGraph(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: an AuxiliaryGraph has only `edges` (1.x `attributes` removed).
    """

    def __init__(self, edges=None):  # noqa: E501
        """AuxiliaryGraph - a model defined in OpenAPI

        :param edges: The edges of this AuxiliaryGraph.  # noqa: E501
        :type edges: List[str]
        """
        self.openapi_types = {
            'edges': List[str]
        }

        self.attribute_map = {
            'edges': 'edges'
        }

        self._edges = edges

    @classmethod
    def from_dict(cls, dikt) -> 'AuxiliaryGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuxiliaryGraph of this AuxiliaryGraph.  # noqa: E501
        :rtype: AuxiliaryGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def edges(self):
        """Gets the edges of this AuxiliaryGraph.

        List of edges that form the AuxiliaryGraph. Each item is a reference to a single KnowledgeGraph Edge.  # noqa: E501

        :return: The edges of this AuxiliaryGraph.
        :rtype: List[str]
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this AuxiliaryGraph.

        List of edges that form the AuxiliaryGraph. Each item is a reference to a single KnowledgeGraph Edge.  # noqa: E501

        :param edges: The edges of this AuxiliaryGraph.
        :type edges: List[str]
        """
        if edges is None:
            raise ValueError("Invalid value for `edges`, must not be `None`")  # noqa: E501

        self._edges = edges
