# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server.models.attribute import Attribute
from shepherd_utils.arax.openapi_server.models.qualifier import Qualifier
from shepherd_utils.arax.openapi_server.models.retrieval_source import RetrievalSource
from shepherd_utils.arax.openapi_server import util

from shepherd_utils.arax.openapi_server.models.attribute import Attribute  # noqa: E501
from shepherd_utils.arax.openapi_server.models.qualifier import Qualifier  # noqa: E501
from shepherd_utils.arax.openapi_server.models.retrieval_source import RetrievalSource  # noqa: E501

class Edge(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: `knowledge_level` and `agent_type` are required top-level Edge properties.
    """

    def __init__(self, predicate=None, subject=None, object=None, attributes=None, qualifiers=None, sources=None, knowledge_level=None, agent_type=None):  # noqa: E501
        """Edge - a model defined in OpenAPI

        :param predicate: The predicate of this Edge.  # noqa: E501
        :type predicate: str
        :param subject: The subject of this Edge.  # noqa: E501
        :type subject: str
        :param object: The object of this Edge.  # noqa: E501
        :type object: str
        :param attributes: The attributes of this Edge.  # noqa: E501
        :type attributes: List[Attribute]
        :param qualifiers: The qualifiers of this Edge.  # noqa: E501
        :type qualifiers: List[Qualifier]
        :param sources: The sources of this Edge.  # noqa: E501
        :type sources: List[RetrievalSource]
        :param knowledge_level: The knowledge_level of this Edge.  # noqa: E501
        :type knowledge_level: str
        :param agent_type: The agent_type of this Edge.  # noqa: E501
        :type agent_type: str
        """
        self.openapi_types = {
            'predicate': str,
            'subject': str,
            'object': str,
            'attributes': List[Attribute],
            'qualifiers': List[Qualifier],
            'sources': List[RetrievalSource],
            'knowledge_level': str,
            'agent_type': str
        }

        self.attribute_map = {
            'predicate': 'predicate',
            'subject': 'subject',
            'object': 'object',
            'attributes': 'attributes',
            'qualifiers': 'qualifiers',
            'sources': 'sources',
            'knowledge_level': 'knowledge_level',
            'agent_type': 'agent_type'
        }

        self._predicate = predicate
        self._subject = subject
        self._object = object
        self._attributes = attributes
        self._qualifiers = qualifiers
        self._sources = sources
        self._knowledge_level = knowledge_level
        self._agent_type = agent_type

    @classmethod
    def from_dict(cls, dikt) -> 'Edge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Edge of this Edge.  # noqa: E501
        :rtype: Edge
        """
        return util.deserialize_model(dikt, cls)

    @property
    def predicate(self):
        """Gets the predicate of this Edge.

        The type of relationship for the statement expressed in an Edge.  # noqa: E501

        :return: The predicate of this Edge.
        :rtype: str
        """
        return self._predicate

    @predicate.setter
    def predicate(self, predicate):
        """Sets the predicate of this Edge.

        The type of relationship for the statement expressed in an Edge.  # noqa: E501

        :param predicate: The predicate of this Edge.
        :type predicate: str
        """
        if predicate is None:
            raise ValueError("Invalid value for `predicate`, must not be `None`")  # noqa: E501

        self._predicate = predicate

    @property
    def subject(self):
        """Gets the subject of this Edge.

        Corresponds to the map key CURIE of the subject concept node of this relationship edge.  # noqa: E501

        :return: The subject of this Edge.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this Edge.

        Corresponds to the map key CURIE of the subject concept node of this relationship edge.  # noqa: E501

        :param subject: The subject of this Edge.
        :type subject: str
        """
        if subject is None:
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def object(self):
        """Gets the object of this Edge.

        Corresponds to the map key CURIE of the object concept node of this relationship edge.  # noqa: E501

        :return: The object of this Edge.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this Edge.

        Corresponds to the map key CURIE of the object concept node of this relationship edge.  # noqa: E501

        :param object: The object of this Edge.
        :type object: str
        """
        if object is None:
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501

        self._object = object

    @property
    def attributes(self):
        """Gets the attributes of this Edge.

        A list of additional attributes for this edge  # noqa: E501

        :return: The attributes of this Edge.
        :rtype: List[Attribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Edge.

        A list of additional attributes for this edge  # noqa: E501

        :param attributes: The attributes of this Edge.
        :type attributes: List[Attribute]
        """

        self._attributes = attributes

    @property
    def qualifiers(self):
        """Gets the qualifiers of this Edge.

        A set of Qualifiers that act together to add nuance or detail to the statement expressed in an Edge.  # noqa: E501

        :return: The qualifiers of this Edge.
        :rtype: List[Qualifier]
        """
        return self._qualifiers

    @qualifiers.setter
    def qualifiers(self, qualifiers):
        """Sets the qualifiers of this Edge.

        A set of Qualifiers that act together to add nuance or detail to the statement expressed in an Edge.  # noqa: E501

        :param qualifiers: The qualifiers of this Edge.
        :type qualifiers: List[Qualifier]
        """

        self._qualifiers = qualifiers

    @property
    def sources(self):
        """Gets the sources of this Edge.

        A list of RetrievalSource objects that provide information about how a particular information resource served as a source from which the knowledge expressed in an Edge was retrieved.  # noqa: E501

        :return: The sources of this Edge.
        :rtype: List[RetrievalSource]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this Edge.

        A list of RetrievalSource objects that provide information about how a particular information resource served as a source from which the knowledge expressed in an Edge was retrieved.  # noqa: E501

        :param sources: The sources of this Edge.
        :type sources: List[RetrievalSource]
        """
        if sources is None:
            raise ValueError("Invalid value for `sources`, must not be `None`")  # noqa: E501

        self._sources = sources

    @property
    def knowledge_level(self):
        """Gets the knowledge_level of this Edge.

        One of the biolink-enumerated permissible values for `knowledge level` that provides the level of knowledge the Edge represents.  # noqa: E501

        :return: The knowledge_level of this Edge.
        :rtype: str
        """
        return self._knowledge_level

    @knowledge_level.setter
    def knowledge_level(self, knowledge_level):
        """Sets the knowledge_level of this Edge.

        One of the biolink-enumerated permissible values for `knowledge level` that provides the level of knowledge the Edge represents.  # noqa: E501

        :param knowledge_level: The knowledge_level of this Edge.
        :type knowledge_level: str
        """
        if knowledge_level is None:
            raise ValueError("Invalid value for `knowledge_level`, must not be `None`")  # noqa: E501

        self._knowledge_level = knowledge_level

    @property
    def agent_type(self):
        """Gets the agent_type of this Edge.

        One of the biolink-enumerated permissible values for `agent type` that provides the kind of agent that originated the knowledge presented by the Edge.  # noqa: E501

        :return: The agent_type of this Edge.
        :rtype: str
        """
        return self._agent_type

    @agent_type.setter
    def agent_type(self, agent_type):
        """Sets the agent_type of this Edge.

        One of the biolink-enumerated permissible values for `agent type` that provides the kind of agent that originated the knowledge presented by the Edge.  # noqa: E501

        :param agent_type: The agent_type of this Edge.
        :type agent_type: str
        """
        if agent_type is None:
            raise ValueError("Invalid value for `agent_type`, must not be `None`")  # noqa: E501

        self._agent_type = agent_type
