# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server import util


class EdgeBinding(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: one EdgeBinding per QEdge, binding one or more KnowledgeGraph Edges by `ids`.
    """

    def __init__(self, ids=None):  # noqa: E501
        """EdgeBinding - a model defined in OpenAPI

        :param ids: The ids of this EdgeBinding.  # noqa: E501
        :type ids: List[str]
        """
        self.openapi_types = {
            'ids': List[str]
        }

        self.attribute_map = {
            'ids': 'ids'
        }

        self._ids = ids

    @classmethod
    def from_dict(cls, dikt) -> 'EdgeBinding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EdgeBinding of this EdgeBinding.  # noqa: E501
        :rtype: EdgeBinding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ids(self):
        """Gets the ids of this EdgeBinding.

        The key identifiers of specific KnowledgeGraph Edges.  # noqa: E501

        :return: The ids of this EdgeBinding.
        :rtype: List[str]
        """
        return self._ids

    @ids.setter
    def ids(self, ids):
        """Sets the ids of this EdgeBinding.

        The key identifiers of specific KnowledgeGraph Edges.  # noqa: E501

        :param ids: The ids of this EdgeBinding.
        :type ids: List[str]
        """
        if ids is None:
            raise ValueError("Invalid value for `ids`, must not be `None`")  # noqa: E501

        self._ids = ids
