# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server.models.meta_attribute import MetaAttribute
from shepherd_utils.arax.openapi_server.models.meta_qualifier import MetaQualifier
from shepherd_utils.arax.openapi_server import util

from shepherd_utils.arax.openapi_server.models.meta_attribute import MetaAttribute  # noqa: E501
from shepherd_utils.arax.openapi_server.models.meta_qualifier import MetaQualifier  # noqa: E501

class MetaEdge(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: gains `knowledge_levels`, `agent_types` and `sources`.
    """

    def __init__(self, subject=None, predicate=None, object=None, knowledge_types=None, attributes=None, qualifiers=None, association=None, knowledge_levels=None, agent_types=None, sources=None):  # noqa: E501
        """MetaEdge - a model defined in OpenAPI

        :param subject: The subject of this MetaEdge.  # noqa: E501
        :type subject: str
        :param predicate: The predicate of this MetaEdge.  # noqa: E501
        :type predicate: str
        :param object: The object of this MetaEdge.  # noqa: E501
        :type object: str
        :param knowledge_types: The knowledge_types of this MetaEdge.  # noqa: E501
        :type knowledge_types: List[str]
        :param attributes: The attributes of this MetaEdge.  # noqa: E501
        :type attributes: List[MetaAttribute]
        :param qualifiers: The qualifiers of this MetaEdge.  # noqa: E501
        :type qualifiers: List[MetaQualifier]
        :param association: The association of this MetaEdge.  # noqa: E501
        :type association: str
        :param knowledge_levels: The knowledge_levels of this MetaEdge.  # noqa: E501
        :type knowledge_levels: List[str]
        :param agent_types: The agent_types of this MetaEdge.  # noqa: E501
        :type agent_types: List[str]
        :param sources: The sources of this MetaEdge.  # noqa: E501
        :type sources: List[str]
        """
        self.openapi_types = {
            'subject': str,
            'predicate': str,
            'object': str,
            'knowledge_types': List[str],
            'attributes': List[MetaAttribute],
            'qualifiers': List[MetaQualifier],
            'association': str,
            'knowledge_levels': List[str],
            'agent_types': List[str],
            'sources': List[str]
        }

        self.attribute_map = {
            'subject': 'subject',
            'predicate': 'predicate',
            'object': 'object',
            'knowledge_types': 'knowledge_types',
            'attributes': 'attributes',
            'qualifiers': 'qualifiers',
            'association': 'association',
            'knowledge_levels': 'knowledge_levels',
            'agent_types': 'agent_types',
            'sources': 'sources'
        }

        self._subject = subject
        self._predicate = predicate
        self._object = object
        self._knowledge_types = knowledge_types
        self._attributes = attributes
        self._qualifiers = qualifiers
        self._association = association
        self._knowledge_levels = knowledge_levels
        self._agent_types = agent_types
        self._sources = sources

    @classmethod
    def from_dict(cls, dikt) -> 'MetaEdge':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MetaEdge of this MetaEdge.  # noqa: E501
        :rtype: MetaEdge
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subject(self):
        """Gets the subject of this MetaEdge.

        Subject node category of this relationship edge.  # noqa: E501

        :return: The subject of this MetaEdge.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this MetaEdge.

        Subject node category of this relationship edge.  # noqa: E501

        :param subject: The subject of this MetaEdge.
        :type subject: str
        """
        if subject is None:
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def predicate(self):
        """Gets the predicate of this MetaEdge.

        Biolink relationship between the subject and object categories.  # noqa: E501

        :return: The predicate of this MetaEdge.
        :rtype: str
        """
        return self._predicate

    @predicate.setter
    def predicate(self, predicate):
        """Sets the predicate of this MetaEdge.

        Biolink relationship between the subject and object categories.  # noqa: E501

        :param predicate: The predicate of this MetaEdge.
        :type predicate: str
        """
        if predicate is None:
            raise ValueError("Invalid value for `predicate`, must not be `None`")  # noqa: E501

        self._predicate = predicate

    @property
    def object(self):
        """Gets the object of this MetaEdge.

        Object node category of this relationship edge.  # noqa: E501

        :return: The object of this MetaEdge.
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this MetaEdge.

        Object node category of this relationship edge.  # noqa: E501

        :param object: The object of this MetaEdge.
        :type object: str
        """
        if object is None:
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501

        self._object = object

    @property
    def knowledge_types(self):
        """Gets the knowledge_types of this MetaEdge.

        A list of knowledge_types that are supported by the service.  # noqa: E501

        :return: The knowledge_types of this MetaEdge.
        :rtype: List[str]
        """
        return self._knowledge_types

    @knowledge_types.setter
    def knowledge_types(self, knowledge_types):
        """Sets the knowledge_types of this MetaEdge.

        A list of knowledge_types that are supported by the service.  # noqa: E501

        :param knowledge_types: The knowledge_types of this MetaEdge.
        :type knowledge_types: List[str]
        """

        self._knowledge_types = knowledge_types

    @property
    def attributes(self):
        """Gets the attributes of this MetaEdge.

        Edge attributes that are supported by the service.  # noqa: E501

        :return: The attributes of this MetaEdge.
        :rtype: List[MetaAttribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this MetaEdge.

        Edge attributes that are supported by the service.  # noqa: E501

        :param attributes: The attributes of this MetaEdge.
        :type attributes: List[MetaAttribute]
        """

        self._attributes = attributes

    @property
    def qualifiers(self):
        """Gets the qualifiers of this MetaEdge.

        Qualifiers that are possible to be found on this edge type.  # noqa: E501

        :return: The qualifiers of this MetaEdge.
        :rtype: List[MetaQualifier]
        """
        return self._qualifiers

    @qualifiers.setter
    def qualifiers(self, qualifiers):
        """Sets the qualifiers of this MetaEdge.

        Qualifiers that are possible to be found on this edge type.  # noqa: E501

        :param qualifiers: The qualifiers of this MetaEdge.
        :type qualifiers: List[MetaQualifier]
        """

        self._qualifiers = qualifiers

    @property
    def association(self):
        """Gets the association of this MetaEdge.

        The Biolink association type (entity) that this edge represents.  # noqa: E501

        :return: The association of this MetaEdge.
        :rtype: str
        """
        return self._association

    @association.setter
    def association(self, association):
        """Sets the association of this MetaEdge.

        The Biolink association type (entity) that this edge represents.  # noqa: E501

        :param association: The association of this MetaEdge.
        :type association: str
        """

        self._association = association

    @property
    def knowledge_levels(self):
        """Gets the knowledge_levels of this MetaEdge.

        The knowledge levels contributing to this meta edge.  # noqa: E501

        :return: The knowledge_levels of this MetaEdge.
        :rtype: List[str]
        """
        return self._knowledge_levels

    @knowledge_levels.setter
    def knowledge_levels(self, knowledge_levels):
        """Sets the knowledge_levels of this MetaEdge.

        The knowledge levels contributing to this meta edge.  # noqa: E501

        :param knowledge_levels: The knowledge_levels of this MetaEdge.
        :type knowledge_levels: List[str]
        """

        self._knowledge_levels = knowledge_levels

    @property
    def agent_types(self):
        """Gets the agent_types of this MetaEdge.

        The agent types contributing to this meta edge.  # noqa: E501

        :return: The agent_types of this MetaEdge.
        :rtype: List[str]
        """
        return self._agent_types

    @agent_types.setter
    def agent_types(self, agent_types):
        """Sets the agent_types of this MetaEdge.

        The agent types contributing to this meta edge.  # noqa: E501

        :param agent_types: The agent_types of this MetaEdge.
        :type agent_types: List[str]
        """

        self._agent_types = agent_types

    @property
    def sources(self):
        """Gets the sources of this MetaEdge.

        The infores CURIEs of the sources contributing to this meta edge.  # noqa: E501

        :return: The sources of this MetaEdge.
        :rtype: List[str]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this MetaEdge.

        The infores CURIEs of the sources contributing to this meta edge.  # noqa: E501

        :param sources: The sources of this MetaEdge.
        :type sources: List[str]
        """

        self._sources = sources
