# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server import util


class PathConstraint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: `intermediate_categories` is renamed `required_intermediate_categories`.
    """

    def __init__(self, required_intermediate_categories=None):  # noqa: E501
        """PathConstraint - a model defined in OpenAPI

        :param required_intermediate_categories: The required_intermediate_categories of this PathConstraint.  # noqa: E501
        :type required_intermediate_categories: List[str]
        """
        self.openapi_types = {
            'required_intermediate_categories': List[str]
        }

        self.attribute_map = {
            'required_intermediate_categories': 'required_intermediate_categories'
        }

        self._required_intermediate_categories = required_intermediate_categories

    @classmethod
    def from_dict(cls, dikt) -> 'PathConstraint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PathConstraint of this PathConstraint.  # noqa: E501
        :rtype: PathConstraint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def required_intermediate_categories(self):
        """Gets the required_intermediate_categories of this PathConstraint.

        A list of Biolink Model categories by which to constrain paths returned (AND).  # noqa: E501

        :return: The required_intermediate_categories of this PathConstraint.
        :rtype: List[str]
        """
        return self._required_intermediate_categories

    @required_intermediate_categories.setter
    def required_intermediate_categories(self, required_intermediate_categories):
        """Sets the required_intermediate_categories of this PathConstraint.

        A list of Biolink Model categories by which to constrain paths returned (AND).  # noqa: E501

        :param required_intermediate_categories: The required_intermediate_categories of this PathConstraint.
        :type required_intermediate_categories: List[str]
        """

        self._required_intermediate_categories = required_intermediate_categories
