# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server.models.allow_deny_constraint import AllowDenyConstraint
from shepherd_utils.arax.openapi_server.models.attribute_constraint import AttributeConstraint
from shepherd_utils.arax.openapi_server.models.source_constraint import SourceConstraint
from shepherd_utils.arax.openapi_server import util

from shepherd_utils.arax.openapi_server.models.allow_deny_constraint import AllowDenyConstraint  # noqa: E501
from shepherd_utils.arax.openapi_server.models.attribute_constraint import AttributeConstraint  # noqa: E501
from shepherd_utils.arax.openapi_server.models.source_constraint import SourceConstraint  # noqa: E501

class QEdgeConstraints(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: all constraints placed on a QEdge (replaces 1.x attribute_constraints / qualifier_constraints).
    """

    def __init__(self, knowledge_level=None, agent_type=None, attributes=None, qualifiers=None, sources=None):  # noqa: E501
        """QEdgeConstraints - a model defined in OpenAPI

        :param knowledge_level: The knowledge_level of this QEdgeConstraints.  # noqa: E501
        :type knowledge_level: AllowDenyConstraint
        :param agent_type: The agent_type of this QEdgeConstraints.  # noqa: E501
        :type agent_type: AllowDenyConstraint
        :param attributes: The attributes of this QEdgeConstraints.  # noqa: E501
        :type attributes: List[AttributeConstraint]
        :param qualifiers: The qualifiers of this QEdgeConstraints.  # noqa: E501
        :type qualifiers: List[Dict[str, str]]
        :param sources: The sources of this QEdgeConstraints.  # noqa: E501
        :type sources: SourceConstraint
        """
        self.openapi_types = {
            'knowledge_level': AllowDenyConstraint,
            'agent_type': AllowDenyConstraint,
            'attributes': List[AttributeConstraint],
            'qualifiers': List[Dict[str, str]],
            'sources': SourceConstraint
        }

        self.attribute_map = {
            'knowledge_level': 'knowledge_level',
            'agent_type': 'agent_type',
            'attributes': 'attributes',
            'qualifiers': 'qualifiers',
            'sources': 'sources'
        }

        self._knowledge_level = knowledge_level
        self._agent_type = agent_type
        self._attributes = attributes
        self._qualifiers = qualifiers
        self._sources = sources

    @classmethod
    def from_dict(cls, dikt) -> 'QEdgeConstraints':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QEdgeConstraints of this QEdgeConstraints.  # noqa: E501
        :rtype: QEdgeConstraints
        """
        return util.deserialize_model(dikt, cls)

    @property
    def knowledge_level(self):
        """Gets the knowledge_level of this QEdgeConstraints.

        knowledge_level values allowed or denied on bound edges.  # noqa: E501

        :return: The knowledge_level of this QEdgeConstraints.
        :rtype: AllowDenyConstraint
        """
        return self._knowledge_level

    @knowledge_level.setter
    def knowledge_level(self, knowledge_level):
        """Sets the knowledge_level of this QEdgeConstraints.

        knowledge_level values allowed or denied on bound edges.  # noqa: E501

        :param knowledge_level: The knowledge_level of this QEdgeConstraints.
        :type knowledge_level: AllowDenyConstraint
        """

        self._knowledge_level = knowledge_level

    @property
    def agent_type(self):
        """Gets the agent_type of this QEdgeConstraints.

        agent_type values allowed or denied on bound edges.  # noqa: E501

        :return: The agent_type of this QEdgeConstraints.
        :rtype: AllowDenyConstraint
        """
        return self._agent_type

    @agent_type.setter
    def agent_type(self, agent_type):
        """Sets the agent_type of this QEdgeConstraints.

        agent_type values allowed or denied on bound edges.  # noqa: E501

        :param agent_type: The agent_type of this QEdgeConstraints.
        :type agent_type: AllowDenyConstraint
        """

        self._agent_type = agent_type

    @property
    def attributes(self):
        """Gets the attributes of this QEdgeConstraints.

        A list of AttributeConstraints applied to a QEdge.  # noqa: E501

        :return: The attributes of this QEdgeConstraints.
        :rtype: List[AttributeConstraint]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this QEdgeConstraints.

        A list of AttributeConstraints applied to a QEdge.  # noqa: E501

        :param attributes: The attributes of this QEdgeConstraints.
        :type attributes: List[AttributeConstraint]
        """

        self._attributes = attributes

    @property
    def qualifiers(self):
        """Gets the qualifiers of this QEdgeConstraints.

        A list of QualifierSetConstraints ({qualifier_type_id: qualifier_value} mappings, OR between sets, AND within one).  # noqa: E501

        :return: The qualifiers of this QEdgeConstraints.
        :rtype: List[Dict[str, str]]
        """
        return self._qualifiers

    @qualifiers.setter
    def qualifiers(self, qualifiers):
        """Sets the qualifiers of this QEdgeConstraints.

        A list of QualifierSetConstraints ({qualifier_type_id: qualifier_value} mappings, OR between sets, AND within one).  # noqa: E501

        :param qualifiers: The qualifiers of this QEdgeConstraints.
        :type qualifiers: List[Dict[str, str]]
        """

        self._qualifiers = qualifiers

    @property
    def sources(self):
        """Gets the sources of this QEdgeConstraints.

        Infores CURIEs allowed or denied in the sources of the bound Edge.  # noqa: E501

        :return: The sources of this QEdgeConstraints.
        :rtype: SourceConstraint
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this QEdgeConstraints.

        Infores CURIEs allowed or denied in the sources of the bound Edge.  # noqa: E501

        :param sources: The sources of this QEdgeConstraints.
        :type sources: SourceConstraint
        """

        self._sources = sources
