# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server.models.q_edge import QEdge
from shepherd_utils.arax.openapi_server.models.q_node import QNode
from shepherd_utils.arax.openapi_server.models.q_path import QPath
from shepherd_utils.arax.openapi_server import util

from shepherd_utils.arax.openapi_server.models.q_edge import QEdge  # noqa: E501
from shepherd_utils.arax.openapi_server.models.q_node import QNode  # noqa: E501
from shepherd_utils.arax.openapi_server.models.q_path import QPath  # noqa: E501

class QueryGraph(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: one QueryGraph (1.x QueryGraph / PathfinderQueryGraph collapse): nodes plus edges and/or paths.
    """

    def __init__(self, nodes=None, edges=None, paths=None):  # noqa: E501
        """QueryGraph - a model defined in OpenAPI

        :param nodes: The nodes of this QueryGraph.  # noqa: E501
        :type nodes: Dict[str, QNode]
        :param edges: The edges of this QueryGraph.  # noqa: E501
        :type edges: Dict[str, QEdge]
        :param paths: The paths of this QueryGraph.  # noqa: E501
        :type paths: Dict[str, QPath]
        """
        self.openapi_types = {
            'nodes': Dict[str, QNode],
            'edges': Dict[str, QEdge],
            'paths': Dict[str, QPath]
        }

        self.attribute_map = {
            'nodes': 'nodes',
            'edges': 'edges',
            'paths': 'paths'
        }

        self._nodes = nodes
        self._edges = edges
        self._paths = paths

    @classmethod
    def from_dict(cls, dikt) -> 'QueryGraph':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryGraph of this QueryGraph.  # noqa: E501
        :rtype: QueryGraph
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes(self):
        """Gets the nodes of this QueryGraph.

        The node specifications.  # noqa: E501

        :return: The nodes of this QueryGraph.
        :rtype: Dict[str, QNode]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this QueryGraph.

        The node specifications.  # noqa: E501

        :param nodes: The nodes of this QueryGraph.
        :type nodes: Dict[str, QNode]
        """
        if nodes is None:
            raise ValueError("Invalid value for `nodes`, must not be `None`")  # noqa: E501

        self._nodes = nodes

    @property
    def edges(self):
        """Gets the edges of this QueryGraph.

        The edge specifications.  # noqa: E501

        :return: The edges of this QueryGraph.
        :rtype: Dict[str, QEdge]
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this QueryGraph.

        The edge specifications.  # noqa: E501

        :param edges: The edges of this QueryGraph.
        :type edges: Dict[str, QEdge]
        """

        self._edges = edges

    @property
    def paths(self):
        """Gets the paths of this QueryGraph.

        The QueryGraph path specification, used only for pathfinder type queries.  # noqa: E501

        :return: The paths of this QueryGraph.
        :rtype: Dict[str, QPath]
        """
        return self._paths

    @paths.setter
    def paths(self, paths):
        """Sets the paths of this QueryGraph.

        The QueryGraph path specification, used only for pathfinder type queries.  # noqa: E501

        :param paths: The paths of this QueryGraph.
        :type paths: Dict[str, QPath]
        """

        self._paths = paths
