# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from shepherd_utils.arax.openapi_server.models.base_model_ import Model
from shepherd_utils.arax.openapi_server import util


class SourceConstraint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TRAPI 2.0: an AllowDenyConstraint on the infores CURIEs in an Edge's sources.
    """

    def __init__(self, behavior=None, values=None, primary_only=None):  # noqa: E501
        """SourceConstraint - a model defined in OpenAPI

        :param behavior: The behavior of this SourceConstraint.  # noqa: E501
        :type behavior: str
        :param values: The values of this SourceConstraint.  # noqa: E501
        :type values: List[str]
        :param primary_only: The primary_only of this SourceConstraint.  # noqa: E501
        :type primary_only: bool
        """
        self.openapi_types = {
            'behavior': str,
            'values': List[str],
            'primary_only': bool
        }

        self.attribute_map = {
            'behavior': 'behavior',
            'values': 'values',
            'primary_only': 'primary_only'
        }

        self._behavior = behavior
        self._values = values
        self._primary_only = primary_only

    @classmethod
    def from_dict(cls, dikt) -> 'SourceConstraint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SourceConstraint of this SourceConstraint.  # noqa: E501
        :rtype: SourceConstraint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def behavior(self):
        """Gets the behavior of this SourceConstraint.

        ALLOW or DENY.  # noqa: E501

        :return: The behavior of this SourceConstraint.
        :rtype: str
        """
        return self._behavior

    @behavior.setter
    def behavior(self, behavior):
        """Sets the behavior of this SourceConstraint.

        ALLOW or DENY.  # noqa: E501

        :param behavior: The behavior of this SourceConstraint.
        :type behavior: str
        """
        if behavior is None:
            raise ValueError("Invalid value for `behavior`, must not be `None`")  # noqa: E501

        self._behavior = behavior

    @property
    def values(self):
        """Gets the values of this SourceConstraint.

        Infores CURIEs to allow or deny.  # noqa: E501

        :return: The values of this SourceConstraint.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this SourceConstraint.

        Infores CURIEs to allow or deny.  # noqa: E501

        :param values: The values of this SourceConstraint.
        :type values: List[str]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values

    @property
    def primary_only(self):
        """Gets the primary_only of this SourceConstraint.

        Apply the constraint only to the primary_knowledge_source (default false).  # noqa: E501

        :return: The primary_only of this SourceConstraint.
        :rtype: bool
        """
        return self._primary_only

    @primary_only.setter
    def primary_only(self, primary_only):
        """Sets the primary_only of this SourceConstraint.

        Apply the constraint only to the primary_knowledge_source (default false).  # noqa: E501

        :param primary_only: The primary_only of this SourceConstraint.
        :type primary_only: bool
        """

        self._primary_only = primary_only
