"""Layer-1 golden parity: Shepherd's ARS ports vs. the real upstream outputs.

tests/fixtures/ars_goldens/goldens.json is generated by RUNNING the pinned
NCATSTranslator/Relay code over tests/fixtures/ars_corpus/ (see
scripts/ars_parity/generate_goldens.py). These tests run the Shepherd ports
over the same corpus and require identical output.

Comparison rules:
  - dicts/scalars: exact
  - lists: exact order first; on mismatch, fall back to multiset equality
    (order-insensitive) -- the upstream code has a few list(set(...)) unions
    whose ordering is hash-seed dependent
  - log-entry "timestamp" values are masked (upstream stamps wall-clock)
"""

import copy
import json
import pathlib

import pytest

from shepherd_utils.ars import filters as ars_filters
from shepherd_utils.ars import merge as ars_merge
from shepherd_utils.ars import premerge as ars_premerge
from shepherd_utils.ars import scoring as ars_scoring
from shepherd_utils.ars.blocklist import load_blocklist, remove_blocked
from shepherd_utils.ars.trapi import validate

FIXTURES = pathlib.Path(__file__).resolve().parents[2] / "fixtures"
CORPUS = FIXTURES / "ars_corpus"
GOLDENS = json.loads((FIXTURES / "ars_goldens/goldens.json").read_text())


def load(name):
    return json.loads((CORPUS / name).read_text())


def _canonical_log_message(msg):
    """Upstream embeds ``str(list)`` built from a set intersection in the
    blocklist log line; sort the bracketed names so the comparison doesn't
    depend on set iteration order."""
    prefix = "Removed the following bad nodes: "
    if isinstance(msg, str) and msg.startswith(prefix):
        import ast

        try:
            names = ast.literal_eval(msg[len(prefix) :])
            return prefix + str(sorted(names))
        except (ValueError, SyntaxError):
            return msg
    return msg


def mask_log_timestamps(obj):
    """Replace 'timestamp' values inside log-entry dicts with a fixed token
    and canonicalize set-order-dependent log messages."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "timestamp" and isinstance(v, str):
                out[k] = "<ts>"
            elif k == "message":
                out[k] = mask_log_timestamps(_canonical_log_message(v))
            else:
                out[k] = mask_log_timestamps(v)
        return out
    if isinstance(obj, list):
        return [mask_log_timestamps(v) for v in obj]
    return obj


def _multiset(items):
    return sorted(json.dumps(i, sort_keys=True, default=str) for i in items)


def assert_parity(actual, golden, path="$"):
    if isinstance(golden, dict):
        assert isinstance(actual, dict), f"{path}: {type(actual)} != dict"
        assert set(actual.keys()) == set(
            golden.keys()
        ), f"{path}: keys {sorted(actual.keys())} != {sorted(golden.keys())}"
        for k in golden:
            assert_parity(actual[k], golden[k], f"{path}.{k}")
    elif isinstance(golden, list):
        assert isinstance(actual, list), f"{path}: {type(actual)} != list"
        assert len(actual) == len(
            golden
        ), f"{path}: length {len(actual)} != {len(golden)}"
        try:
            for i, (a, g) in enumerate(zip(actual, golden)):
                assert_parity(a, g, f"{path}[{i}]")
        except AssertionError:
            # order-insensitive fallback for set-union ordering divergence
            assert _multiset(actual) == _multiset(
                golden
            ), f"{path}: list contents differ (even unordered)"
    elif isinstance(golden, float) or isinstance(actual, float):
        assert actual == pytest.approx(
            golden, rel=1e-9, abs=1e-12
        ), f"{path}: {actual} != {golden}"
    else:
        assert actual == golden, f"{path}: {actual!r} != {golden!r}"


def jsonable(obj):
    def coerce(o):
        try:
            return float(o)
        except (TypeError, ValueError):
            return str(o)

    return json.loads(json.dumps(obj, default=coerce))


# ---------------------------------------------------------------------------
# mergeDicts
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", load("mergedicts_cases.json"), ids=lambda c: c["name"])
def test_mergedicts_parity(case):
    golden = next(g for g in GOLDENS["mergedicts"] if g["name"] == case["name"])
    dc = copy.deepcopy(case["dcurrent"])
    dm = copy.deepcopy(case["dmerged"])
    if "raises" in golden:
        with pytest.raises(Exception):
            ars_merge.mergeDicts(dc, dm)
    else:
        result = ars_merge.mergeDicts(dc, dm)
        assert_parity(jsonable(result), golden["output"])


# ---------------------------------------------------------------------------
# mergeMessages
# ---------------------------------------------------------------------------


def _tmsg(resp):
    return ars_merge.TranslatorMessage(copy.deepcopy(resp["message"]))


def test_merge_ab_parity():
    a, b = load("response_aragorn.json"), load("response_arax.json")
    merged = ars_merge.mergeMessages([_tmsg(a), _tmsg(b)], "pk-ab")
    assert_parity(jsonable(merged.to_dict()), GOLDENS["merge_ab"])


def test_merge_ba_parity():
    a, b = load("response_aragorn.json"), load("response_arax.json")
    merged = ars_merge.mergeMessages([_tmsg(b), _tmsg(a)], "pk-ba")
    assert_parity(jsonable(merged.to_dict()), GOLDENS["merge_ba"])


def test_merge_pipeline_parity():
    """scrub + decorate + normalize_scores on each side, then merge --
    the same shape pre_merge_process + merge_received produce."""
    pipe_a, pipe_b = load("response_aragorn.json"), load("response_arax.json")
    for resp, infores in ((pipe_a, "infores:aragorn"), (pipe_b, "infores:arax")):
        ars_premerge.scrub_null_attributes(resp)
        ars_premerge.decorate_edges_with_infores(resp, infores)
        ars_premerge.normalize_scores(resp, "k", "agent")
    assert_parity(jsonable(pipe_a), GOLDENS["premerged_inputs"]["aragorn"])
    assert_parity(jsonable(pipe_b), GOLDENS["premerged_inputs"]["arax"])
    merged = ars_merge.mergeMessages(
        [
            ars_merge.TranslatorMessage(copy.deepcopy(pipe_a["message"])),
            ars_merge.TranslatorMessage(copy.deepcopy(pipe_b["message"])),
        ],
        "pk-pipe",
    )
    assert_parity(jsonable(merged.to_dict()), GOLDENS["merge_pipeline_ab"])


def test_get_msg_stats_parity():
    a, b = load("response_aragorn.json"), load("response_arax.json")
    merged = ars_merge.mergeMessages([_tmsg(a), _tmsg(b)], "pk-ab")
    assert_parity(
        jsonable(ars_merge.get_msg_stats(merged.to_dict())),
        GOLDENS["get_msg_stats"],
    )


# ---------------------------------------------------------------------------
# premerge pieces
# ---------------------------------------------------------------------------


def test_scrub_parity():
    data = load("scrub_input.json")
    ars_premerge.scrub_null_attributes(data)
    assert_parity(jsonable(data), GOLDENS["scrub"])


@pytest.mark.parametrize("case", load("decorate_cases.json"), ids=lambda c: c["name"])
def test_decorate_parity(case):
    golden = next(g for g in GOLDENS["decorate"] if g["name"] == case["name"])
    data = copy.deepcopy(case["data"])
    if "raises" in golden:
        with pytest.raises(Exception):
            ars_premerge.decorate_edges_with_infores(data, case["inforesid"])
    else:
        ars_premerge.decorate_edges_with_infores(data, case["inforesid"])
        assert_parity(jsonable(data), golden["output"])


@pytest.mark.parametrize("case", load("scores_cases.json"), ids=lambda c: c["name"])
def test_scores_parity(case):
    golden = next(g for g in GOLDENS["scores"] if g["name"] == case["name"])
    if "normalized_raises" in golden:
        with pytest.raises(Exception):
            ars_premerge.normalizeScores(copy.deepcopy(case["results"]))
    else:
        normalized = ars_premerge.normalizeScores(copy.deepcopy(case["results"]))
        assert_parity(jsonable(normalized), golden["normalized"])
    stat = ars_premerge.ScoreStatCalc(copy.deepcopy(case["results"]))
    assert_parity(jsonable(stat), golden["stat"])


def test_normalize_scores_full_parity():
    data = load("response_aragorn.json")
    ars_premerge.normalize_scores(data, "key", "agent")
    assert_parity(jsonable(data), GOLDENS["normalize_scores_full"])


@pytest.mark.parametrize("case", load("scores_cases.json"), ids=lambda c: c["name"])
def test_appraise_confidence_parity(case):
    """appraise_confidence/get_confidence replaced the external Appraiser
    call in post_process (Relay PR #884)."""
    golden = next(
        g for g in GOLDENS["appraise_confidence"] if g["name"] == case["name"]
    )
    results = copy.deepcopy(case["results"])
    if "raises" in golden:
        with pytest.raises(Exception):
            ars_premerge.appraise_confidence(results)
    else:
        ars_premerge.appraise_confidence(results)
        assert_parity(jsonable(results), golden["output"])


def test_remove_phantom_parity():
    data = load("response_aragorn.json")
    del data["message"]["auxiliary_graphs"]["aux1"]
    ars_premerge.remove_phantom_support_graphs(data)
    assert_parity(jsonable(data), GOLDENS["remove_phantom"])
    intact = load("response_aragorn.json")
    ars_premerge.remove_phantom_support_graphs(intact)
    assert_parity(jsonable(intact), GOLDENS["remove_phantom_intact"])


# ---------------------------------------------------------------------------
# scoring
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", load("ordering_cases.json"), ids=lambda c: c["name"])
def test_compute_from_results_parity(case):
    golden = next(
        g for g in GOLDENS["compute_from_results"] if g["name"] == case["name"]
    )
    ranked = ars_scoring.compute_from_results(copy.deepcopy(case["results"]))
    assert_parity(jsonable(ranked), golden["output"])


def test_sugeno_grid_parity():
    for entry in GOLDENS["sugeno_grid"]:
        conf, nov, clin = entry["input"]
        _, weights, sugeno = ars_scoring.compute_sugeno(conf, nov, clin, 0)
        assert_parity(jsonable(weights), entry["weights"])
        assert float(sugeno) == pytest.approx(entry["sugeno"], rel=1e-9)
        assert ars_scoring.compute_weighted_mean(conf, nov, clin, 0) == (
            pytest.approx(entry["weighted_mean"], rel=1e-9)
        )


def test_sugeno_rank_parity():
    for entry in GOLDENS["sugeno_rank"]:
        assert ars_scoring.compute_sugeno_rank(entry["scores"]) == entry["rank"]


# ---------------------------------------------------------------------------
# blocklist
# ---------------------------------------------------------------------------


def test_remove_blocked_parity():
    golden = GOLDENS["remove_blocked"]
    data = load("response_blocklist.json")
    blocklist = load_blocklist()
    pk, removed_nodes, removed_results = remove_blocked(
        data, blocklist, "00000000-0000-0000-0000-00000000abcd"
    )
    assert pk == golden["report_pk"]
    assert_parity(
        jsonable([n.get("name") for n in removed_nodes]),
        golden["removed_node_names"],
    )
    assert len(removed_results) == golden["removed_result_count"]
    assert_parity(
        mask_log_timestamps(jsonable(data)),
        mask_log_timestamps(golden["data"]),
    )


# ---------------------------------------------------------------------------
# filters
# ---------------------------------------------------------------------------


def test_filters_parity():
    fin = load("filters_input.json")
    golden = GOLDENS["filters"]
    assert_parity(
        jsonable(ars_filters.hop_level_filter(copy.deepcopy(fin["results"]), 3)),
        golden["hop_3"],
    )
    assert_parity(
        jsonable(ars_filters.hop_level_filter(copy.deepcopy(fin["results"]), 4)),
        golden["hop_4"],
    )
    assert_parity(
        jsonable(ars_filters.score_filter(copy.deepcopy(fin["results"]), [20, 80])),
        golden["score_20_80"],
    )
    assert_parity(
        jsonable(
            ars_filters.node_type_filter(
                copy.deepcopy(fin["kg_nodes"]), copy.deepcopy(fin["results"]), ["Gene"]
            )
        ),
        golden["node_type_gene"],
    )
    assert_parity(
        jsonable(
            ars_filters.node_type_filter(
                copy.deepcopy(fin["kg_nodes"]),
                copy.deepcopy(fin["results"]),
                ["ChemicalEntity"],
            )
        ),
        golden["node_type_chemical"],
    )
    assert_parity(
        jsonable(
            ars_filters.specific_node_filter(
                copy.deepcopy(fin["results"]), ["NCBIGene:5468"]
            )
        ),
        golden["spec_node"],
    )


# ---------------------------------------------------------------------------
# validation verdicts (Shepherd pydantic models vs reasoner-pydantic)
# ---------------------------------------------------------------------------


def _validate_cases():
    aragorn = load("response_aragorn.json")
    cases = {
        "aragorn": aragorn,
        "arax": load("response_arax.json"),
        "empty": load("response_empty.json"),
        "blocklist": load("response_blocklist.json"),
        "no_message": {"foo": "bar"},
    }
    broken_edge = copy.deepcopy(aragorn)
    del broken_edge["message"]["knowledge_graph"]["edges"]["e1"]["predicate"]
    cases["edge_missing_predicate"] = broken_edge

    broken_result = copy.deepcopy(aragorn)
    del broken_result["message"]["results"][0]["node_bindings"]
    cases["result_missing_node_bindings"] = broken_result

    broken_qg = copy.deepcopy(aragorn)
    broken_qg["message"]["query_graph"]["nodes"]["sn"]["categories"] = "notalist"
    cases["qg_categories_not_list"] = broken_qg

    broken_binding = copy.deepcopy(aragorn)
    del broken_binding["message"]["results"][0]["node_bindings"]["sn"][0]["id"]
    cases["binding_missing_id"] = broken_binding

    broken_kg = copy.deepcopy(aragorn)
    broken_kg["message"]["knowledge_graph"] = {"nodes": {}}
    cases["kg_missing_edges"] = broken_kg

    results_not_list = copy.deepcopy(aragorn)
    results_not_list["message"]["results"] = {"a": 1}
    cases["results_not_list"] = results_not_list
    return cases


@pytest.mark.parametrize("name", sorted(GOLDENS["validate"].keys()))
def test_validate_verdict_parity(name):
    cases = _validate_cases()
    assert (
        validate(cases[name]) == GOLDENS["validate"][name]
    ), f"verdict mismatch for {name}"


def test_normalized_scores_survive_shepherd_blob_codec():
    """Regression: rankdata yields numpy.float64; upstream's stdlib-json
    storage accepts it but Shepherd's orjson blob codec rejects numpy
    scalars, so pre-merged callbacks silently failed to save and merges
    KeyError'd. normalized_score must be a plain float."""
    from shepherd_utils.db import decode_message, encode_message

    results = [{"analyses": [{"score": 0.9}]}, {"analyses": [{"score": 0.1}]}]
    normalized = ars_premerge.normalizeScores(results)
    assert all(type(r["normalized_score"]) is float for r in normalized)
    # the whole premerged payload must round-trip through the blob codec
    payload = {"message": {"results": normalized}}
    assert decode_message(encode_message(payload)) == payload
