name: 'Pull Request Feedback'

on: 
  pull_request:

jobs:
  test:
    name: Run tox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox

  check-format:
    name: Check that code matches Black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
